<?php
/*
	chgoto.php	thesitewizard.com's PHP Redirection script 1.1
	Copyright 2002-2008 by Christopher Heng. All rights reserved.
	http://www.thesitewizard.com/

	This script was generated by thesitewizard Navigation Menu Wizard.
	Get your own customized navigation menu free from
		http://www.thesitewizard.com/
	
	I. LICENCE TERMS
	
	1. You may use this script on your website, with or
	without modifications, free of charge.
	
	2. You may NOT redistribute this script, whether modified
	or not. The script is meant for your personal use on your
	website, and can only be distributed by the author,
	Christopher Heng.
	
	3. THE SCRIPT AND ITS DOCUMENTATION ARE PROVIDED
	"AS IS", WITHOUT WARRANTY OF ANY KIND, NOT EVEN THE
	IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
	PARTICULAR PURPOSE. YOU AGREE TO BEAR ALL RISKS AND
	LIABILITIES ARISING FROM THE USE OF THE SCRIPT,
	ITS DOCUMENTATION AND THE INFORMATION PROVIDED BY THE
	SCRIPTS AND THE DOCUMENTATION.
	
	If you cannot agree to any of the above conditions, you
	may not use the script.
	
	Although it is NOT required, I would be most grateful
	if you could also link to us at:
	
		http://www.thesitewizard.com/
	
	II. INSTALLATION AND CONFIGURATION INSTRUCTIONS

	1. This script requires PHP 4.1 and above to work.

	2. The easiest way to configure the script is to use the
	Wizard on thesitewizard.com. Failing that, do the following:

	a. Set $baseurl to point to your URL. For example, if your
	website is at "http://www.thefreecountry.com/", use the
	following:

		$baseurl = "http://www.thefreecountry.com/" ;

	b. Upload the script to your web directory. Make sure you
	upload it in ASCII mode and not BINARY mode.

	c. Now you need to add a menu to your web page. Here's a
	sample:

	<form action="chgoto.php" method="get">
	<select name="url">
	<option value="index.html" selected="selected">----- Select Page to Go To -----</option>
	<option value="index.html">Main Page</option>
	<option value="feedback.html">Feedback</option>
	<option value="sitemap.html">Site Map</option>
	<option value="links.html">Links</option>
	</select>
	<input type="submit" value="Go!" />
	</form>

	Change the values (currently pointing at "index.html",
	"feedback.html", etc) to the real filenames for your web
	site. You should also change the description (currently
	"Main page", "Feedback", etc) to reflect what you call
	your pages. You can have any number of pages. The filenames
	should be relative to the URL that you set in $baseurl. If
	you have set $baseurl to the null string (""), you will need
	to put the complete URLs (ie, URLs like
	"http://www.thefreecountry.com/index.shtml") for each value.

	If you use frames on your website, and want the page to load
	into a specific frame, say "main", change the form tag as follows:
		<form action="chgoto.php" method="get" target="main">

	III. SUPPORT
	
	There is none. You got it without paying a cent, remember?
	
	IV. CONTACTING THE AUTHOR (BUG REPORTS, LICENSING QUESTIONS)
	
	Please use the feedback form on the website:
		http://www.thesitewizard.com/feedback.php
	
	V. WANT MORE SCRIPTS AND OTHER USEFUL WEBMASTER INFORMATION?

	Subscribe (free) to thesitewizard.com's news feed at
		http://www.thesitewizard.com/thesitewizard.xml
	or just check out
		http://www.thesitewizard.com/

*/

// Note that the baseurl must end with a trailing slash. No filenames
// here. But you can set it to a null string, ie, "".
// $baseurl = "http://www.thesitewizard.com/" ;
$baseurl = "http://ec2-54-179-162-196.ap-southeast-1.compute.amazonaws.com/" ;
$url	= $_REQUEST['url'] ;

header( "Location: " . $baseurl . $url );
exit ;

?>



